const page=document.body.dataset.page||'home';
const links=[['home','index.html','首页'],['about','about.html','关于我们'],['products','products.html','产品中心'],['news','news.html','新闻中心'],['contact','contact.html','联系我们']];
const header=()=>`<div class="topbar"><div class="container"><span>欢迎访问锐界精工企业展示网站</span><div class="top-links"><span>专业家具功能五金解决方案</span><span>服务热线：400-000-0000</span></div></div></div><header class="header"><div class="container"><a class="brand" href="index.html"><i class="brand-mark"></i><span class="brand-name">锐界精工<small>RUIJIE PRECISION</small></span></a><nav class="nav" id="nav">${links.map(x=>`<a class="${page===x[0]?'active':''}" href="${x[1]}">${x[2]}</a>`).join('')}</nav><button class="menu-btn" aria-label="打开导航"><i></i></button></div></header>`;
const footer=()=>`<footer class="footer"><div class="container footer-grid"><div><a class="brand" href="index.html"><i class="brand-mark"></i><span class="brand-name">锐界精工<small>RUIJIE PRECISION</small></span></a><p>专注于家具功能五金的研发与制造，以稳定品质、精密工艺和持续创新，为居住空间提供可靠连接。</p></div><div><h3>快速导航</h3><div class="footer-links">${links.map(x=>`<a href="${x[1]}">${x[2]}</a>`).join('')}</div></div><div><h3>产品系列</h3><div class="footer-links"><a href="products.html">家具连接件</a><a href="products.html">灯光系统</a><a href="products.html">滑轨系列</a><a href="products.html">铰链系列</a></div></div><div><h3>联系我们</h3><p>地址：华南某工业园创新大道 88 号<br>电话：400-000-0000<br>邮箱：hello@example.com<br>工作日：08:30—17:30</p></div></div><div class="footer-bottom"><div class="container">© 2026 锐界精工 · 本站为脱敏前端设计演示，所有品牌与联系信息均为虚构。</div></div></footer><div class="toast" id="toast">提交成功，我们会尽快与您联系</div>`;
const crumbs=t=>`<div class="container breadcrumb">首页　/　<b>${t}</b></div>`;
const subHero=(cn,en,cls='')=>`<section class="sub-hero ${cls}"><div class="container"><h1>${cn}</h1><p>${en}</p></div></section>${crumbs(cn)}`;
const sectionHead=(en,cn)=>`<div class="section-head"><div class="en">${en}</div><h2>${cn}</h2><i class="dash"></i></div>`;
const photo=(seed,w=900,h=600)=>`https://picsum.photos/seed/${seed}/${w}/${h}`;
const home=()=>`<main><section class="hero"><div class="container"><div class="hero-copy"><div class="eyebrow">Precision · Quality · Innovation</div><h1>品质引领<br><em>连接未来</em></h1><p>专注家具功能五金 · 精密制造每一个细节</p><a class="btn" href="products.html">探索产品</a><a class="btn outline" href="about.html">了解我们</a></div></div></section><section class="section"><div class="container">${sectionHead('ABOUT RUIJIE','关于锐界精工')}<div class="intro-grid"><div class="intro-image"></div><div class="intro-copy"><div class="sub">Quality leads · Connecting the future</div><h3>专于精工，<span>始于热爱</span></h3><p>我们是一家专注家具功能五金研发、生产与服务的现代制造企业。以质量为生命，以创新为动力，以服务为品牌依托。持续投入精密加工与自动化检测，只为让每一次连接更加稳定、可靠、长久。</p><a class="learn" href="about.html">进一步了解 <i></i></a></div></div></div></section><section class="section gray"><div class="container">${sectionHead('PRODUCT CENTER','产品中心')}<div class="category-grid">${[['连接件系列','CONNECTOR SERIES'],['灯光系统','LIGHTING SYSTEM'],['滑轨与铰链','SLIDE & HINGE']].map((x,i)=>`<a class="category-card" href="products.html"><div class="category-info"><h3>${x[0]}</h3><p>${x[1]}</p><b>0${i+1}</b></div></a>`).join('')}</div></div></section><div class="feature-strip"><div class="container">${[['12','年制造经验'],['38','精密工序'],['100','品质检测项'],['24h','快速服务响应']].map(x=>`<div class="feature"><div class="num">${x[0]}</div><div>${x[1]}<br>QUALITY ASSURANCE</div></div>`).join('')}</div></div><section class="section"><div class="container">${sectionHead('NEWS CENTER','新闻动态')}<div class="news-grid">${newsCards()}</div></div></section></main>`;
const newsData=[
{day:'18',date:'2026-06-18',title:'企业精益生产体系完成新一轮升级',summary:'围绕产品一致性与交付效率，生产现场完成流程再造与检测节点优化。',seed:'ruijie-news-lean',body:['近日，锐界精工精益生产体系新一轮升级正式完成。本次升级覆盖来料、加工、装配、检测与入库等关键环节，通过更清晰的工序标准和可视化管理，让生产状态能够被及时识别和响应。','在质量控制方面，团队进一步细化了首件确认、过程巡检和成品抽检规则，并在重点工位增加数字化记录。每批产品的材料、设备、人员和检测结果均可追溯，为稳定交付提供了更可靠的依据。','未来，公司将继续围绕减少等待、降低损耗、提升一次合格率展开改善，把精益理念落实到每一道工序，为客户提供更加稳定、高效的家具五金解决方案。']},
{day:'08',date:'2026-06-08',title:'新品功能五金系列正式发布',summary:'面向现代家居场景，推出兼顾结构性能与安装效率的新一代产品方案。',seed:'ruijie-news-product',body:['锐界精工新一代功能五金系列正式发布，产品覆盖连接件、静音铰链、隐藏滑轨及柜内照明等多个应用方向，面向定制家居、办公家具和商业空间提供系统化选择。','新品在结构设计阶段充分考虑安装效率与使用寿命，通过模块化尺寸、快装结构和更友好的调节方式，减少现场安装步骤。同时，关键受力部件经过多轮疲劳测试与盐雾测试，以适应长期高频使用。','公司同步完善了选型资料与技术支持服务，设计师和工程客户可根据柜体尺寸、承重要求及使用场景快速匹配产品。']},
{day:'26',date:'2026-05-26',title:'绿色制造：从材料到工艺的持续改善',summary:'推进能源管理与材料利用率提升，让可靠制造与环境责任同行。',seed:'ruijie-news-green',body:['绿色制造不是单一设备的更新，而是贯穿产品全生命周期的持续改善。锐界精工从材料选用、工艺设计和包装运输三个方向入手，逐步降低生产过程中的能源与资源消耗。','在生产现场，团队通过优化排产减少设备空转，回收可再利用金属边料，并以周转包装替代部分一次性材料。新的表面处理方案也在保证耐腐蚀性能的同时，进一步降低过程排放。','公司将持续记录关键环境指标，并把绿色要求纳入供应商协同与新品评审，让品质、效率与责任成为长期制造能力的一部分。']},
{day:'12',date:'2026-05-12',title:'智能检测中心投入试运行',summary:'引入视觉测量与自动采集设备，进一步提升关键尺寸的检测效率。',seed:'ruijie-news-lab',body:['锐界精工智能检测中心已进入试运行阶段。中心配置视觉测量、轮廓分析和耐久测试设备，可对关键尺寸、表面状态与动作寿命进行更高效的综合验证。','检测数据将与生产批次自动关联，帮助工程团队更快发现趋势并定位问题。对于新品开发，集中化检测也缩短了样件验证周期。','试运行结束后，检测中心将逐步覆盖更多产品系列，并向客户提供更完整的质量数据支持。']},
{day:'28',date:'2026-04-28',title:'校企合作培养精密制造新人才',summary:'与职业院校建立实践基地，为青年技术人才提供真实制造项目。',seed:'ruijie-news-team',body:['锐界精工与本地职业院校共同建立精密制造实践基地，首批学生已完成安全、质量与基础工艺培训，并进入项目实践阶段。','实践课程由企业工程师和院校教师联合设计，内容涵盖识图、测量、设备操作、质量分析和现场改善，让学生在真实项目中理解制造标准。','公司希望通过长期合作，为行业培养更多兼具理论基础和现场能力的青年人才，也为企业持续创新建立人才储备。']}
];
function newsCards(){return newsData.slice(0,3).map((n,i)=>`<a class="news-card" href="news-detail.html?id=${i}"><div class="news-cover" style="background-image:url('${photo(n.seed,760,460)}')"><time class="date-tag">${n.day}<small>${n.date.slice(0,7).replace('-',' / ')}</small></time></div><div class="news-body"><h3>${n.title}</h3><p>${n.summary}</p></div></a>`).join('')}
const about=()=>`<main>${subHero('关于我们','ABOUT US')}<section class="section"><div class="container about-story"><div class="about-photo"></div><div class="story"><div class="eyebrow" style="color:#aaa">OUR STORY</div><h2>以精密制造<br>成就可靠连接</h2><div class="redline"></div><p>锐界精工创立于华南制造业腹地，是一家专注家具功能五金的研发、制造与服务企业。我们用严谨的工程思维理解每一个连接结构，用标准化制造守护每一次产品交付。</p><p>从材料选择、模具开发到精密加工和质量检测，团队始终围绕稳定、耐用、易安装持续改进。面向未来，我们希望成为值得长期信赖的功能五金伙伴。</p></div></div></section><section class="section dark"><div class="container">${sectionHead('OUR VALUES','企业理念')}<div class="values">${[['◇','品质为本','用标准守住每个细节'],['◎','持续创新','用技术回应真实需求'],['△','客户至上','用专业创造长期价值'],['✦','协同共进','用信任凝聚团队力量']].map(x=>`<div class="value"><div class="icon">${x[0]}</div><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div></div></section><section class="section gray"><div class="container">${sectionHead('MANUFACTURING','智造实力')}<div class="intro-grid"><div class="intro-copy"><h3>数字化驱动<span>精益生产</span></h3><p>自动化加工设备、标准化作业流程与全过程质量追溯共同构成稳定制造体系。通过持续优化生产节拍和检测能力，在效率与品质之间建立更好的平衡。</p><a class="learn" href="contact.html">联系我们 <i></i></a></div><div class="intro-image"></div></div></div></section></main>`;
const productNames=['精密偏心连接件','静音缓冲铰链','全拉出隐藏滑轨','嵌入式线性灯','金属柜体拉手','快装层板托','阻尼上翻支撑','柜内感应照明','重型抽屉滑轨'];
const products=()=>`<main>${subHero('产品中心','PRODUCT CENTER','products')}<section class="section"><div class="container catalog"><aside><div class="side-title">产品分类</div><div class="filters">${['全部产品','家具连接件','灯光照明系统','滑轨系列','铰链系列'].map((x,i)=>`<button class="filter ${i===0?'active':''}" data-filter="${i}">${x}</button>`).join('')}</div></aside><div class="product-grid" id="productGrid">${productNames.map((x,i)=>`<article class="product" data-cat="${i%4+1}"><div class="product-img" style="background-image:url('${photo(`ruijie-product-${i+1}`,620,440)}')"></div><div class="product-name">${x}</div></article>`).join('')}</div></div></section></main>`;
const news=()=>`<main>${subHero('新闻中心','NEWS CENTER')}<section class="section"><div class="container">${sectionHead('LATEST INFORMATION','企业资讯')}<div class="news-list">${newsData.map((n,i)=>`<article class="news-row"><a href="news-detail.html?id=${i}" class="news-row-img" style="background-image:url('${photo(n.seed,760,460)}')"></a><div><div class="meta">${n.date}　/　企业新闻</div><h2><a href="news-detail.html?id=${i}">${n.title}</a></h2><p>${n.summary}通过技术、流程与人才的协同，让每一项改善最终落实到产品品质和客户体验之中。</p><a class="learn" href="news-detail.html?id=${i}">阅读更多 <i></i></a></div></article>`).join('')}</div></div></section></main>`;
const newsDetail=()=>{const id=Math.max(0,Math.min(newsData.length-1,Number(new URLSearchParams(location.search).get('id'))||0));const n=newsData[id];return `<main>${subHero('资讯详情','NEWS DETAIL')}<section class="article-section"><article class="article container"><a class="article-back" href="news.html">← 返回企业资讯</a><header><h1>${n.title}</h1><div class="article-meta">发布时间：${n.date}　　来源：锐界精工</div></header><img class="article-cover" src="${photo(`${n.seed}-detail`,1200,680)}" alt="${n.title}">${n.body.map((p,i)=>`${i===1?`<img class="article-inline" src="${photo(`${n.seed}-inside`,1000,600)}" alt="${n.title}现场图片">`:''}<p>${p}</p>`).join('')}<p>每一次改善都来自对细节的关注。锐界精工将继续以客户需求为出发点，以稳定制造为基础，让更可靠的功能五金服务更多空间。</p><nav class="article-nav">${id>0?`<a href="news-detail.html?id=${id-1}"><small>上一篇</small>${newsData[id-1].title}</a>`:'<span></span>'}${id<newsData.length-1?`<a class="next" href="news-detail.html?id=${id+1}"><small>下一篇</small>${newsData[id+1].title}</a>`:'<span></span>'}</nav></article></section></main>`};
const contact=()=>`<main>${subHero('联系我们','CONTACT US')}<section class="section"><div class="container contact-grid"><div class="contact-block"><div class="eyebrow" style="color:#aaa">GET IN TOUCH</div><h2>期待与您建立联系</h2>${[['⌖','公司地址','华南某工业园创新大道 88 号'],['☎','服务热线','400-000-0000'],['✉','电子邮箱','hello@example.com'],['◷','服务时间','周一至周六 08:30—17:30']].map(x=>`<div class="contact-item"><div class="contact-icon">${x[0]}</div><div><strong>${x[1]}</strong><span>${x[2]}</span></div></div>`).join('')}</div><form class="form" id="contactForm"><input required placeholder="您的姓名"><input required placeholder="联系电话"><input placeholder="电子邮箱"><input placeholder="公司名称"><textarea required placeholder="请输入您的需求"></textarea><button class="btn" type="submit">提交留言</button></form></div></section><div class="map"><i class="map-pin"></i></div></main>`;
const render={home,about,products,news,'news-detail':newsDetail,contact}[page]||home;document.getElementById('app').innerHTML=header()+render()+footer();
document.querySelector('.menu-btn')?.addEventListener('click',()=>document.getElementById('nav').classList.toggle('open'));
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');const f=+btn.dataset.filter;document.querySelectorAll('.product').forEach(p=>p.style.display=!f||+p.dataset.cat===f?'block':'none')}));
document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();e.target.reset();const t=document.getElementById('toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)});
